spring:
    data:
        mongodb:
            database: votacao-db
            host: localhost
            password: secret
            port: 27017
            username: admin
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            auto-offset-reset: earliest
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
